version: '3.9'

services:
  api:
    build: .
    links:
      - postgres
    container_name: fastapi-application
    ports:
      - '8000:5000'
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_DB: marketplace_api
    ports:
      - "8056:5432"